services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
     # - "xxx.xxx.xxx.xxx:25565:25565"
    environment:
      EULA: "TRUE"
      MOTD: "Juan is gay lol"
      OPS: Dioxys
      MAX_MEMORY: 14G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 32
      SEED: 4013044327186489796
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/admin/MinecraftData:/data
    restart: unless-stopped
