name: Remote Docker Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh $USER@$HOST << EOF
          cd /home/admin/deployments
          git fetch origin main
          git reset --hard origin/main
          for file in $(git diff --name-only HEAD@{1} HEAD | grep docker-compose.yaml); do
            echo "Deploying $file"
            docker-compose -f $file up -d
          done
        EOF
